github: [ELAVARASAN] # Replace with your GitHub username
patreon: # Replace with your Patreon username (if applicable)
open_collective: # Replace with your Open Collective username (if applicable)
ko_fi: [prince] # Replace with your Ko-fi username
tidelift: # Replace with any Tidelift platform-name/package-name you are associated with
community_bridge: # Replace with any Community Bridge project-name you are involved in
liberapay: # Replace with your Liberapay username (if applicable)
issuehunt: # Replace with your IssueHunt username (if applicable)
otechie: # Replace with your Otechie username (if applicable)
lfx_crowdfunding: # Replace with any LFX Crowdfunding project-name you are associated with
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
   - ['link1', 'link2'] # Add any custom sponsorship URLs you'd like to include
