import { SignIn } from "@clerk/nextjs";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'setXvalue',
    description: 'Generated by Prince',
}


export default function Page() {
    return <SignIn />;
}